name 'df_elasticsearch'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures df_elasticsearch'
long_description 'Installs/Configures df_elasticsearch'
version '0.1.0'

depends 'apt'
depends 'df_java'